<a href="https://colab.research.google.com/github/Venkat-51/data_science/blob/main/TASK_1_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount("/content/drive/")

Mounted at /content/drive/


In [ ]:
#version Check
np.__version__

'1.23.5'

##Creating Array

In [ ]:
array = np.array([1,2,3])
print(array)

[1 2 3]


In [ ]:
two_dimentional_array = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(two_dimentional_array)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
zeros = np.zeros(10)
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
ones = np.ones(5)
print(ones)

[1. 1. 1. 1. 1.]


In [ ]:
# Syntax: np.arange(start, stop, step)
# Generate a sequence from start to (stop - step) with the given step size
# Note: stop value is not included in the sequence

# Example 1: start from 0, stop before 10, with a step of 1
sequence1 = np.arange(0, 10, 1)
print("Example 1:", sequence1)

# Example 2: start from 2, stop before 10, with a step of 2
sequence2 = np.arange(2, 10, 2)
print("Example 2:", sequence2)

# Example 3: start from 1, stop before 5, with a step of 0.5
sequence3 = np.arange(1, 5, 0.5)
print("Example 3:", sequence3)


Example 1: [0 1 2 3 4 5 6 7 8 9]
Example 2: [2 4 6 8]
Example 3: [1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [ ]:
# Example 2: Generate 10 values from 2 to 5
sequence2 = np.linspace(2, 5, 10)
print("Example 2:", sequence2)

# Example 3: Generate 20 values from 1 to 100
sequence3 = np.linspace(1, 100, 20)
print("Example 3:", sequence3)


Example 2: [2.         2.33333333 2.66666667 3.         3.33333333 3.66666667
 4.         4.33333333 4.66666667 5.        ]
Example 3: [  1.           6.21052632  11.42105263  16.63157895  21.84210526
  27.05263158  32.26315789  37.47368421  42.68421053  47.89473684
  53.10526316  58.31578947  63.52631579  68.73684211  73.94736842
  79.15789474  84.36842105  89.57894737  94.78947368 100.        ]


In [ ]:
import numpy as np

# Syntax: np.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
# N: Number of rows (and columns) in the output matrix.
# M: Number of columns in the output matrix. If None, defaults to N.
# k: Index of the diagonal (0 for the main diagonal, positive for diagonals above it, negative for below).
# dtype: Data type of the output array.
# order: Whether to store multi-dimensional data in row-major (C-style) or column-major (Fortran-style) order.

# Example 1: Create a 3x3 identity matrix
identity_matrix_3x3 = np.eye(3)
print("Example 1:")
print(identity_matrix_3x3)

# Example 2: Create a 4x5 identity matrix
identity_matrix_4x5 = np.eye(4, 5)
print("\nExample 2:")
print(identity_matrix_4x5)

# Example 3: Create a 2x2 identity matrix with a different data type (int)
identity_matrix_2x2_int = np.eye(2, dtype=int)
print("\nExample 3:")
print(identity_matrix_2x2_int)


Example 1:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Example 2:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]

Example 3:
[[1 0]
 [0 1]]


##Array Information

In [ ]:
import numpy as np

# Create a NumPy array
my_array = np.array([[1, 2, 3], [4, 5, 6]])

# Get the shape of the array
array_shape = my_array.shape

# Print the result
print("Array:")
print(my_array)
print("\nShape of the array:", array_shape)


Array:
[[1 2 3]
 [4 5 6]]

Shape of the array: (2, 3)


In [ ]:
import numpy as np

# Create NumPy arrays with different dimensions
array_1d = np.array([1, 2, 3, 4, 5])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Get the number of dimensions for each array
ndim_1d = array_1d.ndim
ndim_2d = array_2d.ndim
ndim_3d = array_3d.ndim

# Print the results
print("1D Array:")
print(array_1d)
print("Number of dimensions:", ndim_1d)

print("\n2D Array:")
print(array_2d)
print("Number of dimensions:", ndim_2d)

print("\n3D Array:")
print(array_3d)
print("Number of dimensions:", ndim_3d)

1D Array:
[1 2 3 4 5]
Number of dimensions: 1

2D Array:
[[1 2 3]
 [4 5 6]]
Number of dimensions: 2

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Number of dimensions: 3


In [ ]:
import numpy as np

# Create NumPy arrays with different sizes
array_1d = np.array([1, 2, 3, 4, 5])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Get the size (total number of elements) for each array
size_1d = array_1d.size
size_2d = array_2d.size
size_3d = array_3d.size

# Print the results
print("1D Array:")
print(array_1d)
print("Size of the 1D array:", size_1d)

print("\n2D Array:")
print(array_2d)
print("Size of the 2D array:", size_2d)

print("\n3D Array:")
print(array_3d)
print("Size of the 3D array:", size_3d)


1D Array:
[1 2 3 4 5]
Size of the 1D array: 5

2D Array:
[[1 2 3]
 [4 5 6]]
Size of the 2D array: 6

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Size of the 3D array: 8


In [ ]:
import numpy as np

# Create a NumPy array
my_array = np.array([1, 2, 3, 4, 5])

# Get the data type of the array
data_type = my_array.dtype

# Print the result
print("Array:")
print(my_array)
print("\nData type of the array:", data_type)


Array:
[1 2 3 4 5]

Data type of the array: int64


##Array Operations

In [ ]:
import numpy as np

# Create two NumPy arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Use np.add for element-wise addition
result = np.add(array1, array2)

# Print the result
print("Array 1:", array1)
print("Array 2:", array2)
print("Result of element-wise addition:", result)


Array 1: [1 2 3]
Array 2: [4 5 6]
Result of element-wise addition: [5 7 9]


In [ ]:
import numpy as np

# Create two NumPy arrays
array1 = np.array([4, 7, 9])
array2 = np.array([1, 3, 6])

# Use np.subtract for element-wise subtraction
result = np.subtract(array1, array2)

# Print the result
print("Array 1:", array1)
print("Array 2:", array2)
print("Result of element-wise subtraction:", result)


Array 1: [4 7 9]
Array 2: [1 3 6]
Result of element-wise subtraction: [3 4 3]


In [ ]:
import numpy as np

# Create two NumPy arrays
array1 = np.array([2, 4, 6])
array2 = np.array([3, 2, 1])

# Use np.multiply for element-wise multiplication
result = np.multiply(array1, array2)

# Print the result
print("Array 1:", array1)
print("Array 2:", array2)
print("Result of element-wise multiplication:", result)


Array 1: [2 4 6]
Array 2: [3 2 1]
Result of element-wise multiplication: [6 8 6]


In [ ]:
import numpy as np

# Create two NumPy arrays
array1 = np.array([10, 20, 30])
array2 = np.array([2, 5, 3])

# Use np.divide for element-wise division
result = np.divide(array1, array2)

# Print the result
print("Array 1:", array1)
print("Array 2:", array2)
print("Result of element-wise division:", result)


Array 1: [10 20 30]
Array 2: [2 5 3]
Result of element-wise division: [ 5.  4. 10.]


In [ ]:
import numpy as np

# Create two NumPy arrays representing vectors
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

# Calculate the dot product using np.dot
dot_product = np.dot(vector1, vector2)

# Print the result
print("Vector 1:", vector1)
print("Vector 2:", vector2)
print("Dot product of the vectors:", dot_product)

Vector 1: [1 2 3]
Vector 2: [4 5 6]
Dot product of the vectors: 32


In [ ]:
import numpy as np

# Create two NumPy arrays representing matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Perform matrix multiplication using np.dot
matrix_product = np.dot(matrix1, matrix2)

# Print the result
print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)
print("\nResult of matrix multiplication:")
print(matrix_product)


Matrix 1:
[[1 2]
 [3 4]]

Matrix 2:
[[5 6]
 [7 8]]

Result of matrix multiplication:
[[19 22]
 [43 50]]


In [ ]:
# Alternative syntax for matrix multiplication using the @ operator
matrix_product_operator = matrix1 @ matrix2

# Print the result using the @ operator
print("\nResult using @ operator:")
print(matrix_product_operator)



Result using @ operator:
[[19 22]
 [43 50]]


##Random

In [ ]:
import numpy as np
np.random.seed(0) # seed for reproducibility
x1=np.random.randint(10, size=6) #one-dimensional array
x2=np.random.randint(10, size=(3, 4)) #two-dimensional array
x3=np.random.randint(10, size=(3, 4, 5)) #three-dimensional array

In [ ]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [ ]:
a = np.arange(6)
a2 = a[np.newaxis, :]
a2.shape

(1, 6)